losses:
    - name: topofr_sde_ce
      weight: 1
      loss_fn:
        _target_: src.loss.topofr.TopoFRSDECrossEntropyLoss
        temperature: 1.0
        probability_power: 1.0
        alternate_entropy_sign: True
        gum_iters: 1000
    - name: topofr
      weight: 0.1
      input: images_embeddings
      mixable: False
      loss_fn:
        _target_: src.loss.topofr.TopoFRLoss
        p: 2
        match_edges: symmetric
        max_samples: 64
        normalize_input: True
        normalize_features: True
