train:
  order:
    [
      resize,
      horizontal_flip,
      shift_scale_rotate,
      random_brightness_contrast,
      blur,
      coarse_dropout,
      hue_saturation_value,
      gauss_noise,
      iso_noise,
      motion_blur,
      normalize,
      to_tensor
    ]
  resize:
    _target_: albumentations.Resize
    height: ${img_h}
    width: ${img_w}
    p: 1.0
  horizontal_flip:
    _target_: albumentations.HorizontalFlip
    p: 0.5
  shift_scale_rotate:
    _target_: albumentations.ShiftScaleRotate
    scale_limit: 0.1 
    rotate_limit: [-15, 15]
    shift_limit: 0.05
    border_mode: 2
    p: 0.2
  random_brightness_contrast:
    _target_ : albumentations.RandomBrightnessContrast
    brightness_limit: [-0.15, 0.15]
    contrast_limit: [-0.15, 0.15]
    p: 0.1
  blur:
    _target_ : albumentations.Blur
    blur_limit: [3, 5]
    p: 0.1
  coarse_dropout:
    _target_ : albumentations.CoarseDropout
    max_holes: 8
    min_holes: 4
    max_height: 40
    max_width: 40
    min_height: 20
    min_width: 20
    p: 0.2
  hue_saturation_value:
    _target_ : albumentations.HueSaturationValue
    hue_shift_limit: [-20, 20]
    sat_shift_limit: [-30, 30]
    val_shift_limit: [-20, 20]
    p: 0.1
  gauss_noise:
    _target_ : albumentations.GaussNoise
    var_limit: 0.02 
    p: 0.05
  iso_noise:
    _target_ : albumentations.ISONoise
    intensity: [0.1, 0.5]
    color_shift: [0.01, 0.05]
    p: 0.05
  motion_blur:
    _target_ : albumentations.MotionBlur
    blur_limit: [3, 5]
    p: 0.01
  normalize:
    _target_: albumentations.Normalize
    mean: ${backbone.norm_mean}
    std: ${backbone.norm_std}
    p: 1.0
  to_tensor:
    _target_: albumentations.pytorch.ToTensorV2

valid:
  order:
    [
      resize,
      normalize,
      to_tensor
    ]
  resize:
    _target_: albumentations.Resize
    height: ${img_h}
    width: ${img_w}
    p: 1.0
  normalize:
    _target_: albumentations.Normalize
    mean: ${backbone.norm_mean}
    std: ${backbone.norm_std}
    p: 1.0
  to_tensor:
    _target_: albumentations.pytorch.ToTensorV2