GENERAL:
    RANDOM_STATE : 28 
    DEBUG : False      
    DEVICE: 0         
    USE_WANDB : True   

DATA:
    DATASET_TYPE : 'simple'                                     
    DATA_TYPE : 'general'                                      
    DIR: 
        - "/datasets/metric_learning/product_recognition"
        - "/datasets/metric_learning/mksp_170x170"                                   
    SPLIT_FILE: 
        - "/datasets/metric_learning/product_recognition/folds.csv" 
        - "/datasets/metric_learning/mksp_170x170/folds.csv"                  
    
    TRAIN_AUG: 'soft'        
    FOLD: 0                 
    IMG_SIZE: 170            
    BATCH_SIZE: 500        
    WORKERS: 30               
    BALANCED_SAMPLER: False 

MODEL:
    ENCODER_NAME: 'tf_efficientnetv2_b1.in1k' 
    MARGIN_TYPE: 'arcface'                 
    EMBEDDINGS_SIZE: 64                 
    S : 64                                 
    M : 0.1                                
    K : 10                                 
    DROPOUT_PROB : 0.1                     
    LS_PROB : 0.1                          
    POOL_TYPE : 'avg'                      
    AUTO_SCALE_SIZE : True                 
    EASY_MARGIN : False                    
    FREEZE_BACKBONE : False                

    DYNAMIC_MARGIN:     
    #     HB : 0.5
    #     LB : 0.05
    #     LAMBDA : 0.25

TRAIN:
    LOSS_TYPE : 'cross_entropy' 
    CALCULATE_GAP : False        
    FOCAL_GAMMA : 0.1           
    EPOCHS : 15                 
    RESUME :                    
    LOAD_WEIGHTS:               
    LOAD_EMBEDDER: 

    INCREMENTAL_MARGIN:
        # TYPE  : 'linear'
        # MIN_M : 0.0                

    OPTIMIZER:
        OPTIMIZER_TYPE: 'adamw'   
        LR: 1e-3                
        MOMENTUM: 0.9           
        WEIGHT_DECAY: 1e-2  
        BACKBONE_LR_SCALER :     
        
    SCHEDULER:
        SHEDULER_TYPE: 'cosine' 
        T_MAX: 15               
        ETA_MIN: 1e-6           
    
    AMP: True                   
    WARMUP: False               
    GRADIENT_ACC_STEPS: 5    

MISC:
    RUN_INFO: 'full_dataset'             
    DATASET_INFO: 'full'
    PROJECT_NAME: 'product_recognition'
    TMP: "./work_dirs/"