GENERAL:
    RANDOM_STATE : 28 
    DEBUG : False      
    DEVICE: 0         
    USE_WANDB : True   

DATA:
    DATASET_TYPE : 'simple'                                     
    DATA_TYPE : 'general'                                      
    DIR: 
        - "/datasets/metric_learning/product_recognition"
        - "/datasets/metric_learning/mksp"
        - "/datasets/metric_learning/Stanford_Online_Products/"
        - "/datasets/metric_learning/inshop/"
        - "/datasets/metric_learning/CUB_200_2011/"
        - "/datasets/metric_learning/cars196/"
        # - "/datasets/metric_learning/shopee/"  
        - "/datasets/metric_learning/met/"
        # - "/datasets/metric_learning/products10k/"  
        # - "/datasets/metric_learning/rp2k/"     
        # - "/datasets/metric_learning/aliproducts/"                         
    SPLIT_FILE: 
        - "/datasets/metric_learning/product_recognition/folds.csv" 
        - "/datasets/metric_learning/mksp/folds_train_only.csv"
        - "/datasets/metric_learning/Stanford_Online_Products/dataset_info.csv"
        - "/datasets/metric_learning/inshop/dataset_info.csv"   
        - "/datasets/metric_learning/CUB_200_2011/dataset_info.csv"
        - "/datasets/metric_learning/cars196/dataset_info.csv"
        # - "/datasets/metric_learning/shopee/dataset_info.csv" 
        - "/datasets/metric_learning/met/dataset_info.csv"  
        # - "/datasets/metric_learning/products10k/dataset_info.csv"  
        # - "/datasets/metric_learning/rp2k/dataset_info.csv" 
        # - "/datasets/metric_learning/aliproducts/dataset_info.csv"                  
    
    TRAIN_AUG: 'soft'        
    FOLD: 0                 
    IMG_SIZE: 170            
    BATCH_SIZE: 300        
    WORKERS: 30               
    BALANCED_SAMPLER: False 

MODEL:
    ENCODER_NAME: 'tf_efficientnetv2_b1.in1k' 
    MARGIN_TYPE: 'arcface'                 
    EMBEDDINGS_SIZE: 512                   
    S : 30                                 
    M : 0.5                              
    K : 10                                 
    DROPOUT_PROB : 0.1                     
    LS_PROB : 0.1                          
    POOL_TYPE : 'avg'                      
    AUTO_SCALE_SIZE : False                
    EASY_MARGIN : False                    
    FREEZE_BACKBONE : False                

    DYNAMIC_MARGIN:     
    #     HB : 0.5
    #     LB : 0.05
    #     LAMBDA : 0.25

TRAIN:
    LOSS_TYPE : 'cross_entropy' 
    CALCULATE_GAP : False        
    FOCAL_GAMMA : 0.1           
    EPOCHS : 15                
    RESUME :                    
    LOAD_WEIGHTS:               
    LOAD_EMBEDDER: 

    INCREMENTAL_MARGIN:
        # TYPE  : 'linear'
        # MIN_M : 0.0                

    OPTIMIZER:
        OPTIMIZER_TYPE: 'adamw'   
        LR: 1e-3                
        MOMENTUM: 0.9           
        WEIGHT_DECAY: 1e-2    
        BACKBONE_LR_SCALER : 
        
    SCHEDULER:
        SHEDULER_TYPE: 'cosine' 
        T_MAX: 15               
        ETA_MIN: 1e-6           
    
    AMP: True                   
    WARMUP: False               
    GRADIENT_ACC_STEPS: 5    

MISC:
    RUN_INFO: 'm_0_5_s_30'             
    DATASET_INFO: 'mixed_dataset'
    PROJECT_NAME: 'product_recognition'
    TMP: "./work_dirs/"