name: cars196
type: simple                                     

dir: 
    - /datasets/metric_learning/datasets_opensource/cars196                                  
annotations: 
    - /datasets/metric_learning/datasets_opensource/cars196/dataset_info.csv
                  
fold: 0 

label_column: label
fname_column: file_name
use_bboxes: False

labels_to_ids_path: 