name: cars196
type: simple                                     

dir: 
    - /mnt/datasets/metric_learning/datasets_opensource/cars196                                  
annotations: 
    - /mnt/datasets/metric_learning/datasets_opensource/cars196/dataset_info.csv
                  
fold: 0 

label_column: label
fname_column: file_name
use_bboxes: True

min_n_samples_per_label: 
undersampling_max_n_samples: 
oversampling_min_n_samples:

labels_to_ids_path: 