name: cub_200_2011
type: simple                                     

dir: 
    - /datasets/metric_learning/datasets_opensource/CUB_200_2011                                 
annotations: 
    - /datasets/metric_learning/datasets_opensource/CUB_200_2011/dataset_info.csv
                  
fold: 0 

label_column: label
fname_column: file_name
use_bboxes: False

labels_to_ids_path: 