name: 'dataset_v0'
type: 'simple'                                     

dir: 
    - "/datasets/metric_learning/dataset_v0"                                  
annotations: 
    - "/datasets/metric_learning/dataset_v0/dataset_train.csv" 
                 
fold: 

label_column: 'label'
fname_column: 'file_name'
use_bboxes: False

labels_to_ids_path: 