name: 'dataset_v0'
type: 'simple'                                     

dir: 
    - "/datasets/metric_learning/dataset_v0"                                  
annotations: 
    - "/datasets/metric_learning/dataset_v0/folds.csv" 
                 
norm_type : 'clip'  
fold: 0 

label_column: 'label'
fname_column: 'file_name'
use_bboxes: False

labels_to_ids_path: 