name: 'mixed'
DATASET_TYPE : 'simple'                                     
DATA_TYPE : 'clip'                                      
dir: 
    - "/datasets/metric_learning/product_recognition"
    - "/datasets/metric_learning/mksp_170x170"
    - "/datasets/metric_learning/CUB_200_2011/"
    - "/datasets/metric_learning/Stanford_Online_Products/"
    - "/datasets/metric_learning/cars196/"
    - "/datasets/metric_learning/inshop/"                                   
annotations: 
    - "/datasets/metric_learning/product_recognition/folds.csv" 
    - "/datasets/metric_learning/mksp_170x170/folds.csv"
    - "/datasets/metric_learning/CUB_200_2011/dataset_info.csv"
    - "/datasets/metric_learning/Stanford_Online_Products/dataset_info.csv"
    - "/datasets/metric_learning/cars196/dataset_info.csv"  
    - "/datasets/metric_learning/inshop/dataset_info.csv"                 

TRAIN_AUG: 'soft'        
FOLD: 0                 
IMG_SIZE: 224           
BATCH_SIZE: 500      
WORKERS: 30               
BALANCED_SAMPLER: False 