name: mixed3
type: simple                                         

dir: 
    - /mnt/datasets/metric_learning/datasets_opensource/cars196
    - /mnt/datasets/metric_learning/datasets_opensource/Stanford_Online_Products   
    - /mnt/datasets/metric_learning/datasets_opensource/inshop 
    - /mnt/datasets/metric_learning/datasets_opensource/products10k
    - /mnt/datasets/metric_learning/datasets_opensource/largefinefoodai
    - /datasets/metric_learning/dataset_v0/

annotations: 
    - /mnt/datasets/metric_learning/datasets_opensource/cars196/dataset_info.csv
    - /mnt/datasets/metric_learning/datasets_opensource/Stanford_Online_Products/dataset_info.csv
    - /mnt/datasets/metric_learning/datasets_opensource/inshop/dataset_info.csv
    - /mnt/datasets/metric_learning/datasets_opensource/products10k/dataset_info.csv
    - /mnt/datasets/metric_learning/datasets_opensource/largefinefoodai/dataset_info.csv
    - /datasets/metric_learning/dataset_v0/dataset_info_filtered.csv
                  
fold: 

label_column: label
fname_column: file_name
use_bboxes: True

min_n_samples_per_label: 4
undersampling_max_n_samples: 20
oversampling_min_n_samples: 10

labels_to_ids_path: 