name: products10k
type: simple                                         

dir: 
    - /mnt/datasets/metric_learning/datasets_opensource/products10k

annotations: 
    - /mnt/datasets/metric_learning/datasets_opensource/products10k/dataset_info.csv
                  
fold: 0 

label_column: label
fname_column: file_name
use_bboxes: False

labels_to_ids_path: 