name: rp2k
type: simple                                         

dir: 
    - /mnt/datasets/metric_learning/datasets_opensource/rp2k

annotations: 
    - /mnt/datasets/metric_learning/datasets_opensource/rp2k/dataset_info.csv
                  
fold: 0 

label_column: label
fname_column: file_name
use_bboxes: False

labels_to_ids_path: 