name: sop
type: simple                                         

dir: 
    - /datasets/metric_learning/datasets_opensource/Stanford_Online_Products   

annotations: 
    - /datasets/metric_learning/datasets_opensource/Stanford_Online_Products/dataset_info.csv
                  
fold: 0 

label_column: label
fname_column: file_name
use_bboxes: False

labels_to_ids_path: 