GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DATASET_TYPE : 'general'
    DATA_TYPE : 'general'
    DIR: "/home/ubuntu/datasets/metric_learning/train_set/"
    SPLIT_FILE: "/home/ubuntu/datasets/metric_learning/train_set/folds.csv"
    LABELS_TO_IDS_FILE : "/home/ubuntu/datasets/metric_learning/train_set/labels_to_ids.json"
    IDS_TO_LABELS_FILE : "/home/ubuntu/datasets/metric_learning/train_set/ids_to_labels.json"
    
    TRAIN_AUG: 'soft'
    FOLD: 0
    IMG_SIZE: 224
    BATCH_SIZE: 400
    WORKERS: 8

MODEL:
    ENCODER_NAME: 'efficientnet_b0'
    MARGIN_TYPE: 'adaface'
    EMBEDDINGS_SIZE: 512
    S : 64
    M : 0.5
    K : 10
    DROPOUT_PROB : 0.1
    LS_PROB : 0.1
    POOL_TYPE : 'avg'
    AUTO_SCALE_SIZE : False
    EASY_MARGIN : False 

    DYNAMIC_MARGIN:
        # HB : 0.5
        # LB : 0.05
        # LAMBDA : 0.25

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : False
    FOCAL_GAMMA : 0.1
    EPOCHS : 5
    RESUME : 
    FREEZE_BACKBONE : False
    LOAD_WEIGHTS: work_dirs/ms1m_combined_efficientnet_b0_avg_pooling_continue/best.pt

    OPTIMIZER:
        OPTIMIZER_TYPE: 'sgd'
        LR: 5e-4
        MOMENTUM: 0.9
        WEIGHT_DECAY: 1e-4
        
    SCHEDULER:
        SHEDULER_TYPE: 'cosine'
        T_MAX: 5
        ETA_MIN: 5e-6
    
    AMP: True
    WARMUP: True
    

TEST:
    WEIGHTS: 
    EMBEDDINGS_SAVE_PATH : 

MISC:
    RUN_INFO: 'from_faces_pretrain'
    DATASET_INFO: 'dataset1'
    PROJECT_NAME: 'RETECH metric learning'
    TMP: "./work_dirs/"