GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DIR: "/home/ubuntu/datasets/metric_learning/train_set/"
    SPLIT_FILE: "/home/ubuntu/datasets/metric_learning/train_set/folds.csv"
    LABELS_TO_IDS_FILE : "/home/ubuntu/datasets/metric_learning/train_set/labels_to_ids.json"
    IDS_TO_LABELS_FILE : "/home/ubuntu/datasets/metric_learning/train_set/ids_to_labels.json"
    
    FOLD: 0
    IMG_SIZE: 170
    BATCH_SIZE: 320
    WORKERS: 8

OPTIMIZER:
    OPTIMIZER_TYPE: 'adam'
    LR: 1e-3
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0
    SHEDULER_TYPE: 'cosine'
    T_MAX: 30
    ETA_MIN: 1e-5

MODEL:
    ENCODER_NAME: 'efficientnet_b0'
    MARGIN_TYPE: 'adaface_bn'
    EMBEDDINGS_SIZE: 512
    SCALE_SIZE : 64
    M : 0.01
    K : 10
    DYNAMIC_MARGIN_HB : 0.5
    DYNAMIC_MARGIN_LB : 0.05
    DYNAMIC_MARGIN_LAMBDA : 

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : True
    FOCAL_GAMMA : 0.1
    EPOCHS : 30
    RESUME : 
    FREEZE_BACKBONE : False
    AUG_TYPE: 'super_soft'
    LOAD_WEIGHTS: 
    AUTO_SCALE_SIZE : True
    DROPOUT_PROB : 0.2
    LS_PROB : 0.1

TEST:
    WEIGHTS: 
    EMBEDDINGS_SAVE_PATH : 

MISC:
    RUN_INFO: 'soft_augs_m_0_01'
    TMP: "./work_dirs/"