GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DIR: "/home/ubuntu/datasets/metric_learning/train_set/"
    SPLIT_FILE: "/home/ubuntu/datasets/metric_learning/train_set/folds.csv"
    LABELS_TO_IDS_FILE : "/home/ubuntu/datasets/metric_learning/train_set/labels_to_ids.json"
    IDS_TO_LABELS_FILE : "/home/ubuntu/datasets/metric_learning/train_set/ids_to_labels.json"
    
    TRAIN_AUG: 'soft'
    FOLD: 0
    IMG_SIZE: 224
    BATCH_SIZE: 100
    WORKERS: 8


MODEL:
    ENCODER_NAME: 'efficientnet_b0'
    MARGIN_TYPE: 'adaface'
    EMBEDDINGS_SIZE: 512
    SCALE_SIZE : 64
    M : 0.01
    K : 10
    DROPOUT_PROB : 0.2
    LS_PROB : 0.1
    AUTO_SCALE_SIZE : True
    EASY_MARGIN : False 

    DYNAMIC_MARGIN:
        # HB : 0.5
        # LB : 0.05
        # LAMBDA : 0.25

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : True
    FOCAL_GAMMA : 0.1
    EPOCHS : 50
    RESUME : 
    FREEZE_BACKBONE : False
    LOAD_WEIGHTS: 

    OPTIMIZER:
        OPTIMIZER_TYPE: 'adam'
        LR: 1e-4
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0
        
    SCHEDULER:
        SHEDULER_TYPE: 'cosine'
        T_MAX: 10
        ETA_MIN: 1e-6
    

TEST:
    WEIGHTS: 
    EMBEDDINGS_SAVE_PATH : 

MISC:
    RUN_INFO: 'soft_augs'
    TMP: "./work_dirs/"