defaults:
  - backbone : efficientnetv2_b1
  - head : base
  - margin : arcface
  - distillation/teacher : no_teacher
  - distillation/trainer : default
  - dataset : cars196
  - dataloader: default
  - loss: cross_entropy
  - evaluation/evaluator : default
  - evaluation/data : cars_cub
  - evaluation/knn : faiss
  - scheduler : cosine
  - optimizer : adamw
  - transform : default
  - train/trainer: default
  - train/best_model_criterion: default
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  - _self_

debug : False
ddp: False

embeddings_size: 512
batch_size : 256
epochs : 15
fold: 0 
grad_accum_steps: 4
backbone_lr_scaler: 1e-3
random_state : 28 

img_h: 224
img_w: 224

n_workers: auto
device : 0       
visualize_batch: True  
save_embeddings: False
use_wandb  : True
use_mlflow : True
mlflow_server_uri : https://r3dev-mlflow.rebotics.net/

amp: True
                  
load_checkpoint: 
load_mode: emb

run_info: ''
run_name: '${margin.type}_${backbone.type}_${head.type}_${dataset.name}_img${img_h}x${img_w}_emb${embeddings_size}${run_info}'             
project_name: 'product_recognition_v3'
work_dirs: "./work_dirs/train/"


hydra:
  output_subdir: null 
  run:
    dir: work_dirs/train/${run_name}