defaults:
  - backbone : efficientnetv2_b1
  - head : base
  - dataset : cars196
  - dataloader: default
  - transform : without_augs
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  - _self_

debug : False
ddp: False

embeddings_size: 512
n_components: 128
n_batches: 100

batch_size : 256
fold: 0 
random_state : 28 

img_h: 224
img_w: 224

n_workers: auto
device : 0        
save_embeddings: False

model_type: 'torch' 
model_config: ''
weights: 

run_name: 'run_1'
work_dirs: "./work_dirs/pca/"


hydra:
  output_subdir: null 
  run:
    dir: work_dirs/test/${run_name}