GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DIR: "/home/rkuleev/dataset/retech/metric_learning/train_set/"
    SPLIT_FILE: "/home/rkuleev/dataset/retech/metric_learning/train_set/folds.csv"
    LABELS_TO_IDS_FILE : "/home/rkuleev/dataset/retech/metric_learning/train_set/labels_to_ids.json"
    IDS_TO_LABELS_FILE : "/home/rkuleev/dataset/retech/metric_learning/train_set/ids_to_labels.json"
    FOLD: 0
    IMG_SIZE: 170
    BATCH_SIZE: 100 
    WORKERS: 16

OPTIMIZER:
    OPTIMIZER_TYPE: 'adam'
    LR: 1e-3
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0

    SHEDULER_TYPE: 'cosine'
    T_MAX: 50
    ETA_MIN: 1e-6

MODEL:
    ENCODER_NAME: 'efficientnet_b0'
    MARGIN_TYPE: 'arcface'
    EMBEDDINGS_SIZE: 512
    SCALE_SIZE : 30
    M : 0.01

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : True
    FOCAL_GAMMA : 0.1
    EPOCHS : 50
    RESUME : 
    FREEZE_BACKBONE : False
    AUG_TYPE: 'soft'
    LOAD_WEIGHTS: 
    AUTO_SCALE_SIZE : True
    DROPOUT_PROB : 0.1
    LS_PROB : 0.1

TEST:
    WEIGHTS: 
    EMBEDDINGS_SAVE_PATH : 

MISC:
    RUN_INFO: 'new_dataset_m_0_01'
    TMP: "./work_dirs/"