GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DATASET_TYPE : 'mxdataset'
    DATA_TYPE : 'faces'
    DIR: "/home/ubuntu/datasets/metric_learning/ms1mv3"
    SPLIT_FILE: 
    LABELS_TO_IDS_FILE : 
    IDS_TO_LABELS_FILE : 
    
    TRAIN_AUG: 'soft'
    FOLD: 0
    IMG_SIZE: 112
    BATCH_SIZE: 128
    WORKERS: 8

MODEL:
    ENCODER_NAME: 'efficientnet_b1'
    MARGIN_TYPE: 'arcface'
    EMBEDDINGS_SIZE: 512
    SCALE_SIZE : 64
    M : 0.5
    K : 10
    DROPOUT_PROB : 0.2
    LS_PROB : 0.1
    POOL_TYPE : 'gem'
    AUTO_SCALE_SIZE : True
    EASY_MARGIN : False 

    DYNAMIC_MARGIN:
        HB : 0.5
        LB : 0.05
        LAMBDA : 0.25

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : True
    FOCAL_GAMMA : 0.1
    EPOCHS : 30
    RESUME : 
    FREEZE_BACKBONE : False
    LOAD_WEIGHTS: 

    OPTIMIZER:
        OPTIMIZER_TYPE: 'adam'
        LR: 1e-3
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0
        
    SCHEDULER:
        SHEDULER_TYPE: 'cosine'
        T_MAX: 15
        ETA_MIN: 1e-6
    

TEST:
    WEIGHTS: 
    EMBEDDINGS_SAVE_PATH : 

MISC:
    RUN_INFO: 'dynamic_margin'
    DATASET_INFO: 'ms1m'
    PROJECT_NAME: 'Face recognition'
    TMP: "./work_dirs/"