GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DATASET_TYPE : 'mxdataset'
    DATA_TYPE : 'faces'
    DIR: "/home/ubuntu/datasets/metric_learning/ms1mv3"
    SPLIT_FILE: 
    LABELS_TO_IDS_FILE : 
    IDS_TO_LABELS_FILE : 
    
    TRAIN_AUG: 'super_soft'
    FOLD: 0
    IMG_SIZE: 112
    BATCH_SIZE: 800
    WORKERS: 8

MODEL:
    ENCODER_NAME: 'efficientnet_b0'
    MARGIN_TYPE: 'combined'
    EMBEDDINGS_SIZE: 512
    S : 64
    M : 0.5
    K : 10
    DROPOUT_PROB : 0.1
    LS_PROB : 0.1
    POOL_TYPE : 'avg'
    AUTO_SCALE_SIZE : False
    EASY_MARGIN : False 

    DYNAMIC_MARGIN:
        # HB : 0.5
        # LB : 0.05
        # LAMBDA : 0.25

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : False
    FOCAL_GAMMA : 0.1
    EPOCHS : 5
    RESUME : 
    FREEZE_BACKBONE : False
    LOAD_WEIGHTS: work_dirs/ms1m_combined_efficientnet_b0_avg_pooling_continue/best.pt

    OPTIMIZER:
        OPTIMIZER_TYPE: 'sgd'
        LR: 5e-4
        MOMENTUM: 0.9
        WEIGHT_DECAY: 1e-4
        
    SCHEDULER:
        SHEDULER_TYPE: 'cosine'
        T_MAX: 5
        ETA_MIN: 5e-6
    
    AMP: True
    WARMUP: True
    

TEST:
    WEIGHTS: 
    EMBEDDINGS_SAVE_PATH : 
    FACES_EVALUATION: False
    VAL_TARGETS: ['lfw', 'cfp_fp', 'agedb_30']

MISC:
    RUN_INFO: 'avg_pooling_continue'
    DATASET_INFO: 'ms1m'
    PROJECT_NAME: 'Face recognition'
    TMP: "./work_dirs/"