GENERAL:
    RANDOM_STATE : 28
    DEBUG : False
    DEVICE: 0
    USE_WANDB : True

DATA:
    DIR: "/home/rauf/datasets/retechlabs/metric_learning/final_test/products_images_gt"
    SPLIT_FILE: "/home/rauf/datasets/retechlabs/metric_learning/final_test/products_images_gt/folds_test.csv"
    LABELS_TO_IDS_FILE : "/home/rauf/datasets/retechlabs/metric_learning/final_test/products_images_gt/labels_to_ids.json"
    IDS_TO_LABELS_FILE : "/home/rauf/datasets/retechlabs/metric_learning/final_test/products_images_gt/ids_to_labels.json"
    FOLD: 0
    IMG_SIZE: 170
    BATCH_SIZE: 150 
    WORKERS: 32

OPTIMIZER:
    OPTIMIZER_TYPE: 'adam'
    LR: 1e-3
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.0

    SHEDULER_TYPE: 'cosine'
    T_MAX: 50
    ETA_MIN: 1e-6

MODEL:
    ENCODER_NAME: 'efficientnet_b1'
    MARGIN_TYPE: 'subcenter_arcface'
    EMBEDDINGS_SIZE: 512
    SCALE_SIZE : 30
    M : 0.01
    K : 2
    DYNAMIC_MARGIN_HB : 0.1
    DYNAMIC_MARGIN_LB : 0.01
    DYNAMIC_MARGIN_LAMBDA :

TRAIN:
    LOSS_TYPE : 'cross_entropy'
    CALCULATE_GAP : True
    FOCAL_GAMMA : 0.1
    EPOCHS : 50
    RESUME : 
    FREEZE_BACKBONE : False
    AUG_TYPE: 'soft'
    LOAD_WEIGHTS: 
    AUTO_SCALE_SIZE : True
    DROPOUT_PROB : 0.1
    LS_PROB : 0.1

TEST:
    WEIGHTS: /home/rauf/trained_weights/metric/best_emb_subcenter_efnet1.pt
    EMBEDDINGS_SAVE_PATH : /home/rauf/retechlabs/metric_learning/results/products_gt

MISC:
    RUN_INFO: 'new_dataset_subcenter_k2'
    TMP: "./work_dirs/"